# Generated by Django 5.0.14 on 2025-12-05 03:46

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('datatype', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('decimal', 'Decimal'), ('color', 'Cor (Hex)')], default='text', max_length=20, verbose_name='Tipo de dado')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Atributo',
                'verbose_name_plural': 'Tipos de Atributos',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('display_value', models.CharField(blank=True, help_text='Nome alternativo para exibição (opcional)', max_length=100, verbose_name='Valor de exibição')),
                ('color_hex', models.CharField(blank=True, help_text='Para swatches de cor (#RRGGBB)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Hex')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attributetype', verbose_name='Tipo de Atributo')),
            ],
            options={
                'verbose_name': 'Opção de Atributo',
                'verbose_name_plural': 'Opções de Atributos',
                'ordering': ['display_order', 'value'],
                'unique_together': {('attribute_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Produto',
                'verbose_name_plural': 'historical Produtos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVariant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('name', models.CharField(blank=True, help_text='Nome personalizado (gerado automaticamente se vazio)', max_length=255, verbose_name='Nome')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de custo')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de venda')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço "de" para mostrar desconto', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço comparativo')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Rastrear estoque')),
                ('allow_backorder', models.BooleanField(default=False, verbose_name='Permitir compra sem estoque')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Limite de estoque baixo')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'historical Variante',
                'verbose_name_plural': 'historical Variantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, help_text='Nome personalizado (gerado automaticamente se vazio)', max_length=255, verbose_name='Nome')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de custo')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de venda')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço "de" para mostrar desconto', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço comparativo')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Rastrear estoque')),
                ('allow_backorder', models.BooleanField(default=False, verbose_name='Permitir compra sem estoque')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Limite de estoque baixo')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['product', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('cost', 'Preço de Custo'), ('sell', 'Preço de Venda'), ('compare', 'Preço Comparativo')], max_length=10, verbose_name='Tipo de alteração')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço anterior')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Novo preço')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.variant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Histórico de Preços',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributeoption', verbose_name='Opção de Atributo')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Atributo da Variante',
                'verbose_name_plural': 'Atributos das Variantes',
                'unique_together': {('variant', 'attribute_option')},
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute_options',
            field=models.ManyToManyField(related_name='variants', through='catalog.VariantAttribute', to='catalog.attributeoption', verbose_name='Opções de atributos'),
        ),
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Título SEO')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='Descrição SEO')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_groups', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Grupo de Variantes',
                'verbose_name_plural': 'Grupos de Variantes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariantGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant', verbose_name='Variante')),
                ('variant_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variantgroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Membro do Grupo',
                'verbose_name_plural': 'Membros do Grupo',
                'ordering': ['display_order'],
                'unique_together': {('variant_group', 'variant')},
            },
        ),
        migrations.AddField(
            model_name='variantgroup',
            name='variants',
            field=models.ManyToManyField(related_name='groups', through='catalog.VariantGroupMembership', to='catalog.variant', verbose_name='Variantes'),
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='variants/%Y/%m/', verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.variant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Imagem da Variante',
                'verbose_name_plural': 'Imagens das Variantes',
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='variantgroup',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.variantimage', verbose_name='Imagem destaque'),
        ),
        migrations.AlterUniqueTogether(
            name='variantgroup',
            unique_together={('product', 'slug')},
        ),
    ]
