# Generated by Django 5.0.14 on 2025-12-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_historicalproduct_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
