# Generated by Django 5.0.14 on 2025-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='metadata_attributes',
            field=models.JSONField(blank=True, help_text='JSON dos atributos do produto', null=True, verbose_name='Metadados: Atributos'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='metadata_categories',
            field=models.JSONField(blank=True, help_text='JSON das categorias do produto', null=True, verbose_name='Metadados: Categorias'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='metadata_groups',
            field=models.JSONField(blank=True, help_text='JSON dos grupos do produto', null=True, verbose_name='Metadados: Grupos'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='metadata_variants',
            field=models.JSONField(blank=True, help_text='JSON das variantes do produto', null=True, verbose_name='Metadados: Variantes'),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata_attributes',
            field=models.JSONField(blank=True, help_text='JSON dos atributos do produto', null=True, verbose_name='Metadados: Atributos'),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata_categories',
            field=models.JSONField(blank=True, help_text='JSON das categorias do produto', null=True, verbose_name='Metadados: Categorias'),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata_groups',
            field=models.JSONField(blank=True, help_text='JSON dos grupos do produto', null=True, verbose_name='Metadados: Grupos'),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata_variants',
            field=models.JSONField(blank=True, help_text='JSON das variantes do produto', null=True, verbose_name='Metadados: Variantes'),
        ),
    ]
