# Generated by Django 5.0.14 on 2025-12-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_metadata_json_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='filter_group',
            field=models.CharField(blank=True, help_text='Para agrupar valores similares em filtros (ex: "vermelho" agrupa "Vermelho Ferrari", "Vermelho Bordô")', max_length=100, verbose_name='Grupo de Filtro'),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Se definido, esta opção é específica para este produto. Se vazio, é global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_options', to='catalog.product', verbose_name='Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('attribute_type', 'product', 'value')},
        ),
    ]
